MAIN 

	DEFINE VAR1 BIGINT   
	DEFINE VAR1 BYTE   
	DEFINE VAR1 CHAR(100)
	DEFINE VAR1 CHARACTER  
	DEFINE VAR1 DATE   
	DEFINE VAR1 DATETIME  day to day
	DEFINE VAR1 DEC   
	DEFINE VAR1 DECIMAL(10,2)
	DEFINE VAR1 DECIMAL(10)
	DEFINE VAR1 DOUBLE PRECISION  
	DEFINE VAR1 DYNAMIC ARRAY  
	DEFINE VAR1 FLOAT  
	DEFINE VAR1 INT  
	DEFINE VAR1 INTEGER  
	DEFINE VAR1 MONEY  
	DEFINE VAR1 NCHAR(100)  
	DEFINE VAR1 NUMERIC  
	DEFINE VAR1 NVARCHAR(100)  

end MAIN

function f1() 
	--DEFINE VAR1 INTERVAL  
end function

function f2() 
	DEFINE REC1 RECORD
    VAR1 BIGINT
  END RECORD

	DEFINE REC2 RECORD
    VAR1 CHAR(100),
    VAR1 CHARACTER,
    VAR1 DATE,
    VAR1 DATETIME  day to day,
    VAR1 DEC,
    VAR1 DECIMAL(10,2),
    VAR1 DECIMAL(10),
    VAR1 DOUBLE PRECISION,
    VAR1 FLOAT,
    VAR1 INT,
    VAR1 INTEGER,
    VAR1 MONEY,
    VAR1 NCHAR(100),
    VAR1 NUMERIC,
    VAR1 NVARCHAR(100)
  END RECORD  

end function

