export enum TokenKind {
    program,
    main,
    beginBlock,
    endBlock,
    statment,
    keyword,
    whitespace,
    comment,
    string,
    number,
    constant,
    identifier,
    builtInVar,
    globals,
    operator,
    openOperator,
    closeOperator,
    notSpecified,
    function
  // block,
  // bracket,
  // close_operator,
  // statment,
  // double_operator,
  // expression,
  // function,
  // identifier,
  // list,
  // modular,
  // number,
  // unknown,
  // variable,
  }
  
  export interface IAstNode {
    kind: TokenKind,
    line: number,
    column: number,
    offset: {
        start: number,
        end: number,
    },
    value: string,
} 
